gams-ci: try to build and test with asan

diff --git a/.ci-gams/.gitlab-ci-test.yml b/.ci-gams/.gitlab-ci-test.yml
--- a/.ci-gams/.gitlab-ci-test.yml
+++ b/.ci-gams/.gitlab-ci-test.yml
@@ -1,3 +1,31 @@
+.sh-run-test: &sh-run-test |
+  function runtest() {
+    cmd="$1";
+    testsuite="$2"; 
+    failurefile="$3"; 
+
+    rm -rf "$testsuite"
+    mkdir -p "$testsuite"
+    pushd "$testsuite" > /dev/null || return 1
+
+    # Get the testsuite
+    "$cmd" "$testsuite"
+
+    gams "$testsuite" lo=2 --solver=reshop
+
+    tail -n 1 "$failurefile" | grep -Eq "Failed tests. 0" && echo "$testsuite: SUCCESS"
+    EXIT_CODE=$?
+ 
+    if [ $EXIT_CODE -gt 0 ]; then
+       echo "emplib: FAILURE"
+       cat failures_emp.gms
+    fi
+
+    popd > /dev/null || return 1
+
+    return $EXIT_CODE
+  }
+
 test-leg:
   stage: test
   tags: [puma]
@@ -12,17 +40,12 @@ test-leg:
 
     - export GAMSDIR="/cache/gams-installs/$(cat gams_folder_leg.txt)"
     - export PATH="$GAMSDIR:$PATH"
-    - cp build/output/* "$GAMSDIR"/
 
+    - cp build/output/{*.so,optreshop.def} "$GAMSDIR"/
     - EMPSLV=reshop bash test/gams/test.sh
+    - runtest emplib  goempgo failures_emp.gms
+    - runtest testlib quality failures_qa.gms
 
-    - mkdir emplib && cd emplib && emplib goempgo
-    - gams goempgo lo=2 --solver=reshop
-    - tail -n 1 failures_emp.gms | grep -Eq "Failed tests. 0"; cd ..
-
-    - mkdir quality && cd quality && testlib quality
-    - gams quality lo=2 --solver=reshop
-    - tail -n 1 failures_qa.gms | grep -Eq "Failed tests. 0" ; cd ..
   artifacts:
     name: unittest-results-linux
     paths: [build/test/doctest_results_linux.xml]
@@ -43,17 +66,12 @@ test-debug-leg:
 
     - export GAMSDIR="/cache/gams-installs/$(cat gams_folder_leg.txt)"
     - export PATH="$GAMSDIR:$PATH"
-    - cp build/output/* "$GAMSDIR"/
 
+    - cp build/output/{*.so,optreshop.def} "$GAMSDIR"/
     - EMPSLV=reshop bash test/gams/test.sh
+    - runtest emplib  goempgo failures_emp.gms
+    - runtest testlib quality failures_qa.gms
 
-    - mkdir emplib && cd emplib && emplib goempgo
-    - gams goempgo lo=2 --solver=reshop
-    - tail -n 1 failures_emp.gms | grep -Eq "Failed tests. 0"; cd ..
-
-    - mkdir quality && cd quality && testlib quality
-    - gams quality lo=2 --solver=reshop
-    - tail -n 1 failures_qa.gms | grep -Eq "Failed tests. 0" ; cd ..
   artifacts:
     name: unittest-results-debug-linux
     paths: [build/test/doctest_results_linux.xml]
@@ -73,19 +91,28 @@ test-deg:
     - chmod -R +w gamsdir
     - export GAMSDIR="$(pwd)/gamsdir"
     - export PATH="$GAMSDIR:$PATH"
-    - cp build/output/* "$GAMSDIR"/
 
+    # Run tests with regular reshop
+    - cp build/output/{*.dylib,optreshop.def} "$GAMSDIR"/
     - EMPSLV=reshop bash test/gams/test.sh
+    - runtest emplib  goempgo failures_emp.gms
+    - runtest testlib quality failures_qa.gms
 
-    - mkdir emplib && cd emplib && emplib goempgo
-    - gams goempgo lo=2 --solver=reshop
-    - tail -n 1 failures_emp.gms | grep -Eq "Failed tests. 0"; cd ..
+    # Install GAMS driver with asan
+    - cp build-asan/output/gmsrhp_ux.out "$GAMSDIR"/
+    - cp build-asan/output/gamsconfig_test_asan.yaml "$GAMSDIR"/gamsconfig.yaml
 
-    - mkdir quality && cd quality && testlib quality
-    - gams quality lo=2 --solver=reshop
-    - tail -n 1 failures_qa.gms | grep -Eq "Failed tests. 0" ; cd ..
+    # Test that we indeed call the right executable
+    - RHP_DRIVER_BANNER=1 gams emplib/emp01.gms emp=reshop | grep -q "ReSHOP GAMS testing driver"
 
+    # Run tests with regular reshop
+    - EMPSLV=reshop bash test/gams/test.sh
+    - runtest emplib  goempgo failures_emp.gms
+    - runtest testlib quality failures_qa.gms
+
+    # We need to clean up after yourselves
     - rm -rf gamsdir
+
   artifacts:
     name: unittest-results-deg
     paths: [build/test/doctest_results_deg.xml]
@@ -99,25 +126,36 @@ test-dac:
   script:
     - !reference [.get-gams]
     - !reference [.gams-folder-dac]
+    - *sh-run-test
     - ctest --test-dir build/test --output-junit doctest_results_dac.xml || ctest --test-dir build/test --rerun-failed --output-on-failure
+    - ctest --test-dir build-asan/test || ctest --test-dir build-asan/test --rerun-failed --output-on-failure
 
     - cp -a "$HOME/cache/gams-installs/$(cat gams_folder_dac.txt)" gamsdir
     - chmod -R +w gamsdir
     - export GAMSDIR="$(pwd)/gamsdir"
     - export PATH="$GAMSDIR:$PATH"
-    - cp build/output/* "$GAMSDIR"/
 
+    # Run tests with regular reshop
+    - cp build/output/{*.dylib,optreshop.def} "$GAMSDIR"/
     - EMPSLV=reshop bash test/gams/test.sh
+    - runtest emplib  goempgo failures_emp.gms
+    - runtest testlib quality failures_qa.gms
 
-    - mkdir emplib && cd emplib && emplib goempgo
-    - gams goempgo lo=2 --solver=reshop
-    - tail -n 1 failures_emp.gms | grep -Eq "Failed tests. 0"; cd ..
+    # Install GAMS driver with asan
+    - cp build-asan/output/gmsrhp_ux.out "$GAMSDIR"/
+    - cp build-asan/output/gamsconfig_test_asan.yaml "$GAMSDIR"/gamsconfig.yaml
 
-    - mkdir quality && cd quality && testlib quality
-    - gams quality lo=2 --solver=reshop
-    - tail -n 1 failures_qa.gms | grep -Eq "Failed tests. 0" ; cd ..
+    # Test that we indeed call the right executable
+    - RHP_DRIVER_BANNER=1 gams emplib/emp01.gms emp=reshop | grep -q "ReSHOP GAMS testing driver"
 
+    # Run tests with regular reshop
+    - EMPSLV=reshop bash test/gams/test.sh
+    - runtest emplib  goempgo failures_emp.gms
+    - runtest testlib quality failures_qa.gms
+
+    # We need to clean up after yourselves
     - rm -rf gamsdir
+
   artifacts:
     name: unittest-results-dac
     paths: [build/test/doctest_results_dac.xml]
@@ -167,15 +205,19 @@ test-wei:
     - $gmsdirname = Get-Content mygmsdir.tmp -Raw
     - $GAMS_PATH = "C:\Cache\gams-installs\$gmsdirname"
     - $env:Path = "$GAMS_PATH;" + $env:Path
-    - Copy-Item -Path "build/output/*" -Destination "$GAMS_PATH" -Recurse
+    - Copy-Item -Path "build/output/*.dll" -Destination "$GAMS_PATH"
+    - Copy-Item -Path "gams_link/optreshop.def" -Destination "$GAMS_PATH"
 
     - $env:EMPSLV = "reshop"
     # - bash test/gams/test.sh
 
-      # Run EMP library tests
+      # Run tests with regular reshop
     - Run-Test -Command "emplib.exe" -TestSuite "goempgo" -FailureFile "failures_emp.gms"
+    - Run-Test -Command "testlib.exe" -TestSuite "quality" -FailureFile "failures_qa.gms"
 
-      # Run quality tests
+    - Copy-Item -Path "build-asan/output/gmsrhp_ux.out.exe" -Destination "$GAMS_PATH"
+    - Copy-Item -Path "build-asan/output/gamsconfig_test_asan.yaml" -Destination "$GAMS_PATH"/gamsconfig.yaml
+    - Run-Test -Command "emplib.exe" -TestSuite "goempgo" -FailureFile "failures_emp.gms"
     - Run-Test -Command "testlib.exe" -TestSuite "quality" -FailureFile "failures_qa.gms"
 
   artifacts:
